server:
  port: 9091
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root
    url: jdbc:mysql://127.0.0.1:3306/yqc?characterEncoding=utf8&allowMultiQueries=true
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      one:
        max-active: 100
        min-idle: 20
        max-wait: 2000
  application:
    name: mybatis-plus
mybatis-plus:
  type-aliases-package: com.example.mybatisplus.dto
  mapper-locations: classpath:mapper/**/*.xml
  #config-location: classpath:mybatis-config.xml
  global-config:
    db-config:
      id-type: auto
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
logging:
  level:
    com.example.mybatisplus: debug
